name: Build

on:
  push:
    tags:
      - 'v*'
      - 'release-*'
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: RS_ASIO.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

jobs:
  build:
    runs-on: windows-2022

    permissions:
      contents: write

    steps:
    - name: Checkout current build target
      uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild '${{ env.SOLUTION_FILE_PATH }}' /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }}

    - name: Create Release Package
      run: |
        $stagingName = "$env:GITHUB_REPOSITORY".Split('/')[1]
        mkdir $stagingName
        copy "bin\Win32\${{ env.BUILD_CONFIGURATION }}\RS_ASIO.dll" "$stagingName\"
        copy "bin\Win32\${{ env.BUILD_CONFIGURATION }}\avrt.dll" "$stagingName\"
        copy "dist\RS_ASIO.ini" "$stagingName\"
        copy "LICENSE" "$stagingName\"
        copy "README.md" "$stagingName\"
        powershell -Command "Compress-Archive -Path '$stagingName' -DestinationPath '$stagingName-$env:GITHUB_REF_NAME.zip'"

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: rs2011-asio-*.zip
