name: Build
on:
  push:
    tags:
      - 'v*'
      - 'release-*'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v4
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Build with MSBuild
      run: msbuild  '.\RS_ASIO.sln' /p:Configuration=Release /p:Platform=x86
    - name: Create Release Package
      run: |
        mkdir RS2011-ASIO-Release
        copy "bin\Win32\Release\RS_ASIO.dll" "RS2011-ASIO-Release\"
        copy "bin\Win32\Release\avrt.dll" "RS2011-ASIO-Release\"
        copy "dist\RS_ASIO.ini" "RS2011-ASIO-Release\"
        copy "LICENSE" "RS2011-ASIO-Release\"
        copy "README.md" "RS2011-ASIO-Release\"
        powershell -Command "Compress-Archive -Path 'RS2011-ASIO-Release' -DestinationPath 'RS2011-ASIO-release.zip'"
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: RS2011-ASIO-release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
